lsi: false
safe: true
title: [Projects Blog]
description: [Here are all the projects I have been working on recently]
source: https://github.com/choudhary314/choudhary314.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-cayman
plugins:
  - "jekyll-github-metadata"
